/* =========================================================================
   DADOS DOS PAÍSES  —  "A Europa, País a País"
   -------------------------------------------------------------------------
   Lista JSON dentro de uma variável (window.PAISES). A única diferença para
   um .json puro é a linha de atribuição no início — assim o livro-europa.html
   lê os dados abrindo o ficheiro directamente (file://), sem servidor web.

   Editar: mexe nos valores e reabre o livro-europa.html.
   - A ORDEM da lista = ordem no livro (por região, de Portugal para fora).
   - Os RANKINGS de população/área são calculados; não é preciso escrevê-los.
   - "ue": true acrescenta o emoji da UE à linha do governo.
   - "foto": ligação Wikimedia Commons (Special:FilePath). Muda ?width= para
     pedir outro tamanho. Créditos em CREDITOS-FOTOS.md.
   ========================================================================= */
window.PAISES = [
  {
    "nome": "Portugal",
    "endonimo": "Portugal",
    "iso": "pt",
    "ue": true,
    "capital": "Lisboa",
    "populacao": 10467000,
    "area": 92230,
    "moeda": "Euro (€)",
    "idioma": "Português (e mirandês)",
    "governo": "República semipresidencial",
    "monumento": "Mosteiro dos Jerónimos, Lisboa",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Jer%C3%B3nimos_Monastery_in_Bel%C3%A9m%2C_Lisbon%2C_20250604_1342_9260.jpg?width=620",
    "fotoCredito": "Jerónimos Monastery in Belém, Lisbon, 20250604 1342 9260.jpg — Jakub Hałun / CC BY 4.0 · Wikimedia Commons",
    "curiosidade": "A Livraria Bertrand, no Chiado, abriu em 1732 e é a livraria mais antiga do mundo ainda em funcionamento."
  },
  {
    "nome": "Espanha",
    "endonimo": "España",
    "iso": "es",
    "ue": true,
    "capital": "Madrid",
    "populacao": 48450000,
    "area": 505990,
    "moeda": "Euro (€)",
    "idioma": "Espanhol (castelhano)",
    "governo": "Monarquia parlamentar",
    "monumento": "Basílica da Sagrada Família, Barcelona",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Sagrada_Familia_01.jpg?width=620",
    "fotoCredito": "Sagrada Familia 01.jpg — Bernard Gagnon / CC BY-SA 3.0 · Wikimedia Commons",
    "curiosidade": "Tem a maior rede de comboios de alta velocidade da Europa e a segunda maior do mundo, a seguir à China."
  },
  {
    "nome": "Andorra",
    "endonimo": "Andorra",
    "iso": "ad",
    "ue": false,
    "capital": "Andorra-a-Velha",
    "populacao": 81000,
    "area": 468,
    "moeda": "Euro (€)",
    "idioma": "Catalão",
    "governo": "Co-principado parlamentar",
    "monumento": "Casa de la Vall, Andorra-a-Velha",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Casa_de_la_Vall%2C_Andorra_la_Vieja%2C_Andorra%2C_2013-12-30%2C_DD_01.JPG?width=620",
    "fotoCredito": "Casa de la Vall, Andorra la Vieja, Andorra, 2013-12-30, DD 01.JPG — Diego Delso / CC BY-SA 3.0 · Wikimedia Commons",
    "curiosidade": "Os chefes de Estado são dois: o Presidente da França e o bispo de Urgel, em Espanha."
  },
  {
    "nome": "França",
    "endonimo": "France",
    "iso": "fr",
    "ue": true,
    "capital": "Paris",
    "populacao": 68400000,
    "area": 551695,
    "moeda": "Euro (€)",
    "idioma": "Francês",
    "governo": "República semipresidencial",
    "monumento": "Torre Eiffel, Paris",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Eiffel_tower_from_trocadero.jpg?width=620",
    "fotoCredito": "Eiffel tower from trocadero.jpg — NonOmnisMoriar / CC BY-SA 3.0 · Wikimedia Commons",
    "curiosidade": "É o país mais visitado do mundo, com cerca de 100 milhões de turistas por ano."
  },
  {
    "nome": "Mónaco",
    "endonimo": "Monaco",
    "iso": "mc",
    "ue": false,
    "capital": "Mónaco (cidade-Estado)",
    "populacao": 38350,
    "area": 2,
    "moeda": "Euro (€)",
    "idioma": "Francês",
    "governo": "Monarquia constitucional (principado)",
    "monumento": "Palácio do Príncipe / Casino de Monte Carlo",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Le_casino_de_Monte-Carlo.JPG?width=620",
    "fotoCredito": "Le casino de Monte-Carlo.JPG — Fruitpunchline / CC BY-SA 4.0 · Wikimedia Commons",
    "curiosidade": "É o segundo país mais pequeno do mundo e o mais densamente povoado de todos."
  },
  {
    "nome": "Itália",
    "endonimo": "Italia",
    "iso": "it",
    "ue": true,
    "capital": "Roma",
    "populacao": 58900000,
    "area": 301340,
    "moeda": "Euro (€)",
    "idioma": "Italiano",
    "governo": "República parlamentar",
    "monumento": "Coliseu, Roma",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Colosseum_in_Rome-April_2007-1-_copie_2B.jpg?width=620",
    "fotoCredito": "Colosseum in Rome-April 2007-1- copie 2B.jpg — Diliff / CC BY-SA 2.5 · Wikimedia Commons",
    "curiosidade": "É um dos países com mais sítios Património Mundial da UNESCO, a par da China."
  },
  {
    "nome": "San Marino",
    "endonimo": "San Marino",
    "iso": "sm",
    "ue": false,
    "capital": "Cidade de San Marino",
    "populacao": 33600,
    "area": 61,
    "moeda": "Euro (€)",
    "idioma": "Italiano",
    "governo": "República parlamentar",
    "monumento": "As Três Torres de San Marino (Guaita)",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Fortress_of_Guaita_2013-09-19.jpg?width=620",
    "fotoCredito": "Fortress of Guaita 2013-09-19.jpg — Max_Ryazanov / CC BY-SA 3.0 · Wikimedia Commons",
    "curiosidade": "Diz ser a república mais antiga do mundo ainda em atividade, fundada, reza a tradição, no ano 301."
  },
  {
    "nome": "Vaticano",
    "endonimo": "Città del Vaticano",
    "iso": "va",
    "ue": false,
    "capital": "Cidade do Vaticano",
    "populacao": 800,
    "area": 0.49,
    "moeda": "Euro (€)",
    "idioma": "Italiano (latim, na Santa Sé)",
    "governo": "Monarquia absoluta eletiva (o Papa)",
    "monumento": "Basílica de São Pedro",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Basilica_di_San_Pietro_in_Vaticano_September_2015-1a.jpg?width=620",
    "fotoCredito": "Basilica di San Pietro in Vaticano September 2015-1a.jpg — Alvesgaspar / CC BY-SA 4.0 · Wikimedia Commons",
    "curiosidade": "É o país mais pequeno do mundo, tanto em área como em população."
  },
  {
    "nome": "Malta",
    "endonimo": "Malta",
    "iso": "mt",
    "ue": true,
    "capital": "Valeta",
    "populacao": 542000,
    "area": 316,
    "moeda": "Euro (€)",
    "idioma": "Maltês e inglês",
    "governo": "República parlamentar",
    "monumento": "Templos megalíticos de Ġgantija, Gozo",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Templo_de_%C4%A0gantija%2C_isla_de_Gozo%2C_Malta%2C_2021-08-23%2C_DD_35.jpg?width=620",
    "fotoCredito": "Templo de Ġgantija, isla de Gozo, Malta, 2021-08-23, DD 35.jpg — Diego Delso / CC BY-SA 4.0 · Wikimedia Commons",
    "curiosidade": "Os seus templos de pedra são mais antigos do que as pirâmides do Egito e do que Stonehenge."
  },
  {
    "nome": "Reino Unido",
    "endonimo": "United Kingdom",
    "iso": "gb",
    "ue": false,
    "capital": "Londres",
    "populacao": 68350000,
    "area": 243610,
    "moeda": "Libra esterlina (£)",
    "idioma": "Inglês",
    "governo": "Monarquia parlamentar",
    "monumento": "Palácio de Westminster e o Big Ben, Londres",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Big_Ben_at_sunset_-_2014-10-27_17-30.jpg?width=620",
    "fotoCredito": "Big Ben at sunset - 2014-10-27 17-30.jpg — Colin / CC BY-SA 4.0 · Wikimedia Commons",
    "curiosidade": "O metropolitano de Londres, aberto em 1863, é o mais antigo do mundo."
  },
  {
    "nome": "Irlanda",
    "endonimo": "Éire",
    "iso": "ie",
    "ue": true,
    "capital": "Dublin",
    "populacao": 5300000,
    "area": 70273,
    "moeda": "Euro (€)",
    "idioma": "Irlandês e inglês",
    "governo": "República parlamentar",
    "monumento": "Penhascos de Moher, Condado de Clare",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Ireland_Cliffs_of_Moher_BW_2025-09-11_14-27-51.jpg?width=620",
    "fotoCredito": "Ireland Cliffs of Moher BW 2025-09-11 14-27-51.jpg — Berthold Werner / CC BY-SA 4.0 · Wikimedia Commons",
    "curiosidade": "Não há cobras na ilha — o clima frio do fim das glaciações nunca deixou que chegassem."
  },
  {
    "nome": "Bélgica",
    "endonimo": "België / Belgique / Belgien",
    "iso": "be",
    "ue": true,
    "capital": "Bruxelas",
    "populacao": 11750000,
    "area": 30528,
    "moeda": "Euro (€)",
    "idioma": "Neerlandês, francês e alemão",
    "governo": "Monarquia parlamentar federal",
    "monumento": "Manneken Pis, Bruxelas",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Manneken_Pis%2C_Brussels_%28DSCF4467%29.jpg?width=620",
    "fotoCredito": "Manneken Pis, Brussels (DSCF4467).jpg — Trougnouf / CC BY 4.0 · Wikimedia Commons",
    "curiosidade": "Produz mais de 200 mil toneladas de chocolate por ano — o aeroporto de Bruxelas é o maior ponto de venda de chocolate do mundo."
  },
  {
    "nome": "Países Baixos",
    "endonimo": "Nederland",
    "iso": "nl",
    "ue": true,
    "capital": "Amesterdão (governo na Haia)",
    "populacao": 17950000,
    "area": 41850,
    "moeda": "Euro (€)",
    "idioma": "Neerlandês (e frísio)",
    "governo": "Monarquia parlamentar",
    "monumento": "Os moinhos de Kinderdijk",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/The_windmills_of_Kinderdijk.JPG?width=620",
    "fotoCredito": "The windmills of Kinderdijk.JPG — Tarod / CC BY-SA 3.0 nl · Wikimedia Commons",
    "curiosidade": "Cerca de um terço do país está abaixo do nível do mar, protegido por diques."
  },
  {
    "nome": "Luxemburgo",
    "endonimo": "Lëtzebuerg",
    "iso": "lu",
    "ue": true,
    "capital": "Luxemburgo",
    "populacao": 672000,
    "area": 2586,
    "moeda": "Euro (€)",
    "idioma": "Luxemburguês, francês e alemão",
    "governo": "Monarquia constitucional (grão-ducado)",
    "monumento": "Cidade velha e fortificações do Bock, Luxemburgo",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Luxembourg_%28LU%29%2C_Grund_und_%C3%89glise_Saint-Jean_--_2023_--_8132.jpg?width=620",
    "fotoCredito": "Luxembourg (LU), Grund und Église Saint-Jean -- 2023 -- 8132.jpg — Dietmar Rabich / CC BY-SA 4.0 · Wikimedia Commons",
    "curiosidade": "Foi o primeiro país do mundo a tornar todos os transportes públicos gratuitos, em 2020."
  },
  {
    "nome": "Alemanha",
    "endonimo": "Deutschland",
    "iso": "de",
    "ue": true,
    "capital": "Berlim",
    "populacao": 84500000,
    "area": 357590,
    "moeda": "Euro (€)",
    "idioma": "Alemão",
    "governo": "República parlamentar federal",
    "monumento": "Portão de Brandemburgo, Berlim",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Brandenburg_Gate_Quadriga_at_Night.jpg?width=620",
    "fotoCredito": "Brandenburg Gate Quadriga at Night.jpg — א (Aleph)\n\nCreator: Johann Gottfried Schadow / CC BY-SA 2.5 · Wikimedia Commons",
    "curiosidade": "Em muitos troços das autoestradas (Autobahn) não há limite de velocidade."
  },
  {
    "nome": "Suíça",
    "endonimo": "Schweiz / Suisse / Svizzera / Svizra",
    "iso": "ch",
    "ue": false,
    "capital": "Berna",
    "populacao": 8850000,
    "area": 41285,
    "moeda": "Franco suíço (CHF)",
    "idioma": "Alemão, francês, italiano e romanche",
    "governo": "República federal (democracia direta)",
    "monumento": "Monte Cervino (Matterhorn), Zermatt",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/CH.VS.Zermatt_2021-10-17_Matterhorn_8726.jpg?width=620",
    "fotoCredito": "CH.VS.Zermatt 2021-10-17 Matterhorn 8726.jpg — Roy Egloff / CC BY-SA 4.0 · Wikimedia Commons",
    "curiosidade": "Os cidadãos são chamados a votar em referendos nacionais três a quatro vezes por ano."
  },
  {
    "nome": "Listenstaine",
    "endonimo": "Liechtenstein",
    "iso": "li",
    "ue": false,
    "capital": "Vaduz",
    "populacao": 40000,
    "area": 160,
    "moeda": "Franco suíço (CHF)",
    "idioma": "Alemão",
    "governo": "Monarquia constitucional (principado)",
    "monumento": "Castelo de Vaduz",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Liechtenstein_asv2022-10_img22_Vaduz_Schloss.jpg?width=620",
    "fotoCredito": "Liechtenstein asv2022-10 img22 Vaduz Schloss.jpg — A.Savin / FAL · Wikimedia Commons",
    "curiosidade": "É um dos maiores fabricantes mundiais de dentes postiços e não tem exército desde 1868."
  },
  {
    "nome": "Áustria",
    "endonimo": "Österreich",
    "iso": "at",
    "ue": true,
    "capital": "Viena",
    "populacao": 9130000,
    "area": 83879,
    "moeda": "Euro (€)",
    "idioma": "Alemão",
    "governo": "República parlamentar federal",
    "monumento": "Palácio de Schönbrunn, Viena",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Schoenbrunn_Palace_as_seen_from_Neptune_Fountain%2C_September_2016.jpg?width=620",
    "fotoCredito": "Schoenbrunn Palace as seen from Neptune Fountain, September 2016.jpg — Martin Falbisoner / CC BY-SA 4.0 · Wikimedia Commons",
    "curiosidade": "Salzburgo é a cidade natal de Mozart; a música clássica é quase uma marca nacional."
  },
  {
    "nome": "Dinamarca",
    "endonimo": "Danmark",
    "iso": "dk",
    "ue": true,
    "capital": "Copenhaga",
    "populacao": 5960000,
    "area": 43094,
    "moeda": "Coroa dinamarquesa (DKK)",
    "idioma": "Dinamarquês",
    "governo": "Monarquia parlamentar",
    "monumento": "A Pequena Sereia, Copenhaga",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/The_Little_Mermaid_home.jpg?width=620",
    "fotoCredito": "The Little Mermaid home.jpg — klndonnelly / CC BY 2.0 · Wikimedia Commons",
    "curiosidade": "A monarquia dinamarquesa é a mais antiga da Europa, com mais de mil anos de história."
  },
  {
    "nome": "Noruega",
    "endonimo": "Norge / Noreg",
    "iso": "no",
    "ue": false,
    "capital": "Oslo",
    "populacao": 5550000,
    "area": 385207,
    "moeda": "Coroa norueguesa (NOK)",
    "idioma": "Norueguês (e sami)",
    "governo": "Monarquia parlamentar",
    "monumento": "O fiorde de Geiranger",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Geirangerfjord_from_%C3%98rnesvingen%2C_2013_June.jpg?width=620",
    "fotoCredito": "Geirangerfjord from Ørnesvingen, 2013 June.jpg — Ximonic (Simo Räsänen) / CC BY-SA 3.0 · Wikimedia Commons",
    "curiosidade": "Todos os anos oferece a Londres a grande árvore de Natal da Trafalgar Square, desde 1947."
  },
  {
    "nome": "Suécia",
    "endonimo": "Sverige",
    "iso": "se",
    "ue": true,
    "capital": "Estocolmo",
    "populacao": 10550000,
    "area": 450295,
    "moeda": "Coroa sueca (SEK)",
    "idioma": "Sueco",
    "governo": "Monarquia parlamentar",
    "monumento": "Câmara Municipal de Estocolmo, onde é servido o banquete Nobel",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Stockholms_stadshus_February_2026_02.jpg?width=620",
    "fotoCredito": "Stockholms stadshus February 2026 02.jpg — ArildV / CC BY-SA 4.0 · Wikimedia Commons",
    "curiosidade": "Os prémios Nobel são entregues em Estocolmo — só o da Paz é entregue em Oslo."
  },
  {
    "nome": "Islândia",
    "endonimo": "Ísland",
    "iso": "is",
    "ue": false,
    "capital": "Reiquiavique",
    "populacao": 390000,
    "area": 103000,
    "moeda": "Coroa islandesa (ISK)",
    "idioma": "Islandês",
    "governo": "República parlamentar",
    "monumento": "Cascata de Gullfoss",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Gullfoss%2C_Su%C3%B0urland%2C_Islandia%2C_2014-08-16%2C_DD_119.JPG?width=620",
    "fotoCredito": "Gullfoss, Suðurland, Islandia, 2014-08-16, DD 119.JPG — Diego Delso / CC BY-SA 4.0 · Wikimedia Commons",
    "curiosidade": "Não tem exército e quase toda a eletricidade vem de energia geotérmica e das quedas de água."
  },
  {
    "nome": "Finlândia",
    "endonimo": "Suomi",
    "iso": "fi",
    "ue": true,
    "capital": "Helsínquia",
    "populacao": 5580000,
    "area": 338455,
    "moeda": "Euro (€)",
    "idioma": "Finlandês e sueco",
    "governo": "República semipresidencial",
    "monumento": "Fortaleza marítima de Suomenlinna, Helsínquia",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Suomenlinna.jpg?width=620",
    "fotoCredito": "Suomenlinna.jpg — Michal Pise, Michal.Pise / CC BY 2.0 · Wikimedia Commons",
    "curiosidade": "Há cerca de 3 milhões de saunas para 5,5 milhões de habitantes — mais saunas do que carros. A palavra \"sauna\" é finlandesa."
  },
  {
    "nome": "Estónia",
    "endonimo": "Eesti",
    "iso": "ee",
    "ue": true,
    "capital": "Taline",
    "populacao": 1370000,
    "area": 45335,
    "moeda": "Euro (€)",
    "idioma": "Estónio",
    "governo": "República parlamentar",
    "monumento": "Cidade Velha de Taline",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Tallinn-panorama-2011.jpg?width=620",
    "fotoCredito": "Tallinn-panorama-2011.jpg — acediscovery / CC BY 4.0 · Wikimedia Commons",
    "curiosidade": "Foi o primeiro país do mundo a permitir o voto pela internet em eleições nacionais, em 2005."
  },
  {
    "nome": "Letónia",
    "endonimo": "Latvija",
    "iso": "lv",
    "ue": true,
    "capital": "Riga",
    "populacao": 1870000,
    "area": 64589,
    "moeda": "Euro (€)",
    "idioma": "Letão",
    "governo": "República parlamentar",
    "monumento": "Centro histórico de Riga",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/House_of_Blackheads_and_St._Peter%27s_Church_Tower%2C_Riga%2C_Latvia_-_Diliff.jpg?width=620",
    "fotoCredito": "House of Blackheads and St. Peter's Church Tower, Riga, Latvia - Diliff.jpg — Diliff / CC BY-SA 3.0 · Wikimedia Commons",
    "curiosidade": "Riga tem a maior concentração de arquitetura arte nova (jugendstil) da Europa."
  },
  {
    "nome": "Lituânia",
    "endonimo": "Lietuva",
    "iso": "lt",
    "ue": true,
    "capital": "Vílnius",
    "populacao": 2860000,
    "area": 65300,
    "moeda": "Euro (€)",
    "idioma": "Lituano",
    "governo": "República semipresidencial",
    "monumento": "Colina das Cruzes, Šiauliai",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Hill_of_Crosses_1%2C_Siauliai%2C_Lithuania.JPG?width=620",
    "fotoCredito": "Hill of Crosses 1, Siauliai, Lithuania.JPG — Diliff / CC BY-SA 3.0 · Wikimedia Commons",
    "curiosidade": "O lituano é uma das línguas vivas mais antigas da Europa e conserva formas muito próximas do sânscrito."
  },
  {
    "nome": "Polónia",
    "endonimo": "Polska",
    "iso": "pl",
    "ue": true,
    "capital": "Varsóvia",
    "populacao": 36700000,
    "area": 312700,
    "moeda": "Zlóti (PLN)",
    "idioma": "Polaco",
    "governo": "República parlamentar",
    "monumento": "Castelo Real de Wawel, Cracóvia",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Wawel_Castle_view_from_south._Krakow%2C_Poland.jpg?width=620",
    "fotoCredito": "Wawel Castle view from south. Krakow, Poland.jpg — Ввласенко / CC BY-SA 3.0 · Wikimedia Commons",
    "curiosidade": "A cidade velha de Varsóvia foi reconstruída pedra a pedra depois de destruída na Segunda Guerra Mundial."
  },
  {
    "nome": "Chéquia",
    "endonimo": "Česko",
    "iso": "cz",
    "ue": true,
    "capital": "Praga",
    "populacao": 10870000,
    "area": 78871,
    "moeda": "Coroa checa (CZK)",
    "idioma": "Checo",
    "governo": "República parlamentar",
    "monumento": "Castelo de Praga e a Ponte Carlos",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Prague_07-2016_View_from_Petrinska_Tower_img2.jpg?width=620",
    "fotoCredito": "Prague 07-2016 View from Petrinska Tower img2.jpg — A.Savin / FAL · Wikimedia Commons",
    "curiosidade": "É o país onde se bebe mais cerveja por pessoa no mundo."
  },
  {
    "nome": "Eslováquia",
    "endonimo": "Slovensko",
    "iso": "sk",
    "ue": true,
    "capital": "Bratislava",
    "populacao": 5420000,
    "area": 49035,
    "moeda": "Euro (€)",
    "idioma": "Eslovaco",
    "governo": "República parlamentar",
    "monumento": "Castelo de Spiš",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Spissky_hrad_west.jpg?width=620",
    "fotoCredito": "Spissky hrad west.jpg — Ingo Mehling / CC BY-SA 4.0 · Wikimedia Commons",
    "curiosidade": "Tem mais castelos e palácios por habitante do que qualquer outro país."
  },
  {
    "nome": "Hungria",
    "endonimo": "Magyarország",
    "iso": "hu",
    "ue": true,
    "capital": "Budapeste",
    "populacao": 9580000,
    "area": 93028,
    "moeda": "Forint (HUF)",
    "idioma": "Húngaro",
    "governo": "República parlamentar",
    "monumento": "Parlamento de Budapeste",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Budapest_Parliament_4604.JPG?width=620",
    "fotoCredito": "Budapest Parliament 4604.JPG — Dirk Beyer / CC BY-SA 3.0 · Wikimedia Commons",
    "curiosidade": "O metro de Budapeste (1896) é o mais antigo da Europa continental."
  },
  {
    "nome": "Eslovénia",
    "endonimo": "Slovenija",
    "iso": "si",
    "ue": true,
    "capital": "Liubliana",
    "populacao": 2120000,
    "area": 20273,
    "moeda": "Euro (€)",
    "idioma": "Esloveno",
    "governo": "República parlamentar",
    "monumento": "Lago de Bled e a sua ilhota com igreja",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Bled_Island_in_Lake_Bled%2C_Slovenia%2C_20240504_0901_8297.jpg?width=620",
    "fotoCredito": "Bled Island in Lake Bled, Slovenia, 20240504 0901 8297.jpg — Jakub Hałun / CC BY 4.0 · Wikimedia Commons",
    "curiosidade": "Mais de metade do território está coberto de floresta — um dos países mais arborizados da Europa."
  },
  {
    "nome": "Croácia",
    "endonimo": "Hrvatska",
    "iso": "hr",
    "ue": true,
    "capital": "Zagrebe",
    "populacao": 3850000,
    "area": 56594,
    "moeda": "Euro (€)",
    "idioma": "Croata",
    "governo": "República parlamentar",
    "monumento": "Muralhas da cidade velha de Dubrovnik",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/City_walls_of_Dubrovnik_05.jpg?width=620",
    "fotoCredito": "City walls of Dubrovnik 05.jpg — Bernard Gagnon / CC BY-SA 4.0 · Wikimedia Commons",
    "curiosidade": "A gravata nasceu aqui: a palavra francesa \"cravate\" vem de \"croata\", pelos lenços que os soldados croatas usavam ao pescoço."
  },
  {
    "nome": "Bósnia e Herzegovina",
    "endonimo": "Bosna i Hercegovina",
    "iso": "ba",
    "ue": false,
    "capital": "Sarajevo",
    "populacao": 3170000,
    "area": 51197,
    "moeda": "Marco conversível (BAM)",
    "idioma": "Bósnio, croata e sérvio",
    "governo": "República federal parlamentar",
    "monumento": "Ponte Velha (Stari Most), Mostar",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Mostar_Old_Town_Panorama_2007.jpg?width=620",
    "fotoCredito": "Mostar Old Town Panorama 2007.jpg — Ramirez / CC BY-SA 4.0 · Wikimedia Commons",
    "curiosidade": "Sarajevo recebeu os Jogos Olímpicos de Inverno de 1984."
  },
  {
    "nome": "Sérvia",
    "endonimo": "Srbija",
    "iso": "rs",
    "ue": false,
    "capital": "Belgrado",
    "populacao": 6620000,
    "area": 77474,
    "moeda": "Dinar sérvio (RSD)",
    "idioma": "Sérvio",
    "governo": "República parlamentar",
    "monumento": "Fortaleza de Belgrado (Kalemegdan)",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Belgrade_Fortress_Kalemegdan-9878.NEF.jpg?width=620",
    "fotoCredito": "Belgrade Fortress Kalemegdan-9878.NEF.jpg — Zcvetkovic / CC BY-SA 4.0 · Wikimedia Commons",
    "curiosidade": "É um dos maiores produtores mundiais de framboesas."
  },
  {
    "nome": "Montenegro",
    "endonimo": "Crna Gora",
    "iso": "me",
    "ue": false,
    "capital": "Podgorica",
    "populacao": 617000,
    "area": 13812,
    "moeda": "Euro (€)",
    "idioma": "Montenegrino",
    "governo": "República parlamentar",
    "monumento": "Baía de Kotor e a sua cidade fortificada",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/20090719_Crkva_Gospa_od_Zdravlja_Kotor_Bay_Montenegro.jpg?width=620",
    "fotoCredito": "20090719 Crkva Gospa od Zdravlja Kotor Bay Montenegro.jpg — User:Ggia / CC BY-SA 3.0 · Wikimedia Commons",
    "curiosidade": "Usa o euro no dia a dia sem pertencer à zona euro nem à União Europeia."
  },
  {
    "nome": "Kosovo",
    "endonimo": "Kosova / Kosovo",
    "iso": "xk",
    "ue": false,
    "capital": "Pristina",
    "populacao": 1600000,
    "area": 10887,
    "moeda": "Euro (€)",
    "idioma": "Albanês e sérvio",
    "governo": "República parlamentar",
    "monumento": "Mosteiro de Visoki Dečani",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Visoki_De%C4%8Dani_monastery%2C_2008.jpg?width=620",
    "fotoCredito": "Visoki Dečani monastery, 2008.jpg — a.dombrowski / CC BY-SA 2.0 · Wikimedia Commons",
    "curiosidade": "É o país mais recente da Europa: declarou independência em 2008 e tem uma das populações mais jovens do continente."
  },
  {
    "nome": "Albânia",
    "endonimo": "Shqipëria",
    "iso": "al",
    "ue": false,
    "capital": "Tirana",
    "populacao": 2740000,
    "area": 28748,
    "moeda": "Lek (ALL)",
    "idioma": "Albanês",
    "governo": "República parlamentar",
    "monumento": "Cidade-museu de Gjirokastër",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Gjirokast%C3%ABr_Old_Town_%282%29.jpg?width=620",
    "fotoCredito": "Gjirokastër Old Town (2).jpg — Radosław Botev / CC BY 3.0 pl · Wikimedia Commons",
    "curiosidade": "Durante a ditadura foram construídos mais de 170 mil pequenos bunkers de betão, muitos ainda espalhados pelo país."
  },
  {
    "nome": "Macedónia do Norte",
    "endonimo": "Severna Makedonija",
    "iso": "mk",
    "ue": false,
    "capital": "Escópia",
    "populacao": 1830000,
    "area": 25713,
    "moeda": "Denar (MKD)",
    "idioma": "Macedónio e albanês",
    "governo": "República parlamentar",
    "monumento": "Lago de Ohrid e a igreja de São João de Kaneo",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Church_of_St._John_at_Kaneo_6.jpg?width=620",
    "fotoCredito": "Church of St. John at Kaneo 6.jpg — kallerna / CC BY-SA 4.0 · Wikimedia Commons",
    "curiosidade": "O Lago de Ohrid é um dos lagos mais antigos e profundos do mundo, com cerca de três milhões de anos."
  },
  {
    "nome": "Grécia",
    "endonimo": "Elláda (Ελλάδα)",
    "iso": "gr",
    "ue": true,
    "capital": "Atenas",
    "populacao": 10400000,
    "area": 131957,
    "moeda": "Euro (€)",
    "idioma": "Grego",
    "governo": "República parlamentar",
    "monumento": "Acrópole de Atenas e o Partenón",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Attica_06-13_Athens_50_View_from_Philopappos_-_Acropolis_Hill.jpg?width=620",
    "fotoCredito": "Attica 06-13 Athens 50 View from Philopappos - Acropolis Hill.jpg — A.Savin / CC BY-SA 3.0 · Wikimedia Commons",
    "curiosidade": "Foi aqui, na Antiga Olímpia, que nasceram os Jogos Olímpicos, há mais de 2700 anos."
  },
  {
    "nome": "Bulgária",
    "endonimo": "Balgariya (България)",
    "iso": "bg",
    "ue": true,
    "capital": "Sófia",
    "populacao": 6440000,
    "area": 110994,
    "moeda": "Lev (BGN)",
    "idioma": "Búlgaro",
    "governo": "República parlamentar",
    "monumento": "Mosteiro de Rila",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Rila_Monastery%2C_August_2013.jpg?width=620",
    "fotoCredito": "Rila Monastery, August 2013.jpg — Raggatt2000 / CC BY-SA 3.0 · Wikimedia Commons",
    "curiosidade": "Aqui, abanar a cabeça de um lado para o outro quer dizer \"sim\", e acenar de cima para baixo quer dizer \"não\"."
  },
  {
    "nome": "Roménia",
    "endonimo": "România",
    "iso": "ro",
    "ue": true,
    "capital": "Bucareste",
    "populacao": 19000000,
    "area": 238398,
    "moeda": "Leu romeno (RON)",
    "idioma": "Romeno",
    "governo": "República semipresidencial",
    "monumento": "Castelo de Bran, na Transilvânia",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Bran_Castle%2C_Transylvania_%282023%29.jpg?width=620",
    "fotoCredito": "Bran Castle, Transylvania (2023).jpg — Paul Colin Hennig firstdorsal.eu / CC BY-SA 4.0 · Wikimedia Commons",
    "curiosidade": "O Palácio do Parlamento, em Bucareste, é o edifício administrativo mais pesado do mundo."
  },
  {
    "nome": "Moldávia",
    "endonimo": "Moldova",
    "iso": "md",
    "ue": false,
    "capital": "Chișinău",
    "populacao": 2510000,
    "area": 33846,
    "moeda": "Leu moldavo (MDL)",
    "idioma": "Romeno",
    "governo": "República parlamentar",
    "monumento": "Mosteiro rupestre de Orheiul Vechi",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/OrheiulVechi%2CCaveMonastery.jpg?width=620",
    "fotoCredito": "OrheiulVechi,CaveMonastery.jpg — Bertramz / CC BY-SA 3.0 · Wikimedia Commons",
    "curiosidade": "A cave de vinhos de Mileștii Mici tem mais de 200 km de galerias subterrâneas — a maior coleção de garrafas do mundo."
  },
  {
    "nome": "Turquia",
    "endonimo": "Türkiye",
    "iso": "tr",
    "ue": false,
    "capital": "Ancara",
    "populacao": 85300000,
    "area": 783562,
    "moeda": "Lira turca (TRY)",
    "idioma": "Turco",
    "governo": "República presidencial",
    "monumento": "Santa Sofia (Hagia Sophia), Istambul",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Hagia_Sophia_Mars_2013.jpg?width=620",
    "fotoCredito": "Hagia Sophia Mars 2013.jpg — Arild Vågen / CC BY-SA 3.0 · Wikimedia Commons",
    "curiosidade": "Istambul é a única cidade grande do mundo assente em dois continentes — metade na Europa, metade na Ásia."
  },
  {
    "nome": "Chipre",
    "endonimo": "Kýpros (Κύπρος) / Kıbrıs",
    "iso": "cy",
    "ue": true,
    "capital": "Nicósia",
    "populacao": 1340000,
    "area": 9251,
    "moeda": "Euro (€)",
    "idioma": "Grego e turco",
    "governo": "República presidencial",
    "monumento": "Sítio arqueológico de Kourion",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Kourion_archaeological_site_Cyprus_%281%29.jpg?width=620",
    "fotoCredito": "Kourion archaeological site Cyprus (1).jpg — Radosław Botev / CC BY 3.0 pl · Wikimedia Commons",
    "curiosidade": "Nicósia é a última capital do mundo dividida em duas por uma linha de fronteira dentro da própria cidade."
  },
  {
    "nome": "Ucrânia",
    "endonimo": "Ukraïna (Україна)",
    "iso": "ua",
    "ue": false,
    "capital": "Kiev",
    "populacao": 38000000,
    "area": 603628,
    "moeda": "Hryvnia (UAH)",
    "idioma": "Ucraniano",
    "governo": "República semipresidencial",
    "monumento": "Catedral de Santa Sofia, Kiev",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/80-391-9014_Kyiv_Sofia_2_RB_24.jpg?width=620",
    "fotoCredito": "80-391-9014 Kyiv Sofia 2 RB 24.jpg — Rbrechko / CC BY-SA 4.0 · Wikimedia Commons",
    "curiosidade": "É o maior país situado inteiramente dentro da Europa."
  },
  {
    "nome": "Bielorrússia",
    "endonimo": "Belarus (Беларусь)",
    "iso": "by",
    "ue": false,
    "capital": "Minsk",
    "populacao": 9200000,
    "area": 207600,
    "moeda": "Rublo bielorrusso (BYN)",
    "idioma": "Bielorrusso e russo",
    "governo": "República presidencial",
    "monumento": "Castelo de Mir",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/%D0%9A%D0%BE%D0%BC%D0%BF%D0%BB%D0%B5%D0%BA%D1%81_%D0%9C%D0%B8%D1%80%D1%81%D0%BA%D0%BE%D0%B3%D0%BE_%D0%B7%D0%B0%D0%BC%D0%BA%D0%B0.JPG?width=620",
    "fotoCredito": "Комплекс Мирского замка.JPG — Вадзім Новикаў / CC BY-SA 3.0 · Wikimedia Commons",
    "curiosidade": "A floresta de Białowieża, que partilha com a Polónia, é a última grande floresta primitiva da Europa e abriga bisontes selvagens."
  },
  {
    "nome": "Rússia",
    "endonimo": "Rossiya (Россия)",
    "iso": "ru",
    "ue": false,
    "capital": "Moscovo",
    "populacao": 143800000,
    "area": 17098246,
    "moeda": "Rublo russo (RUB)",
    "idioma": "Russo",
    "governo": "República federal semipresidencial",
    "monumento": "Praça Vermelha e a Catedral de São Basílio, Moscovo",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Moscow._Saint_Basil%27s_Cathedral_P4162276_2750.jpg?width=620",
    "fotoCredito": "Moscow. Saint Basil's Cathedral P4162276 2750.jpg — Alexxx1979 / CC BY-SA 4.0 · Wikimedia Commons",
    "curiosidade": "É o maior país do mundo e estende-se por 11 fusos horários, entre a Europa e a Ásia."
  },
  {
    "nome": "Geórgia",
    "endonimo": "Sakartvelo (საქართველო)",
    "iso": "ge",
    "ue": false,
    "capital": "Tbilisi",
    "populacao": 3700000,
    "area": 69700,
    "moeda": "Lari (GEL)",
    "idioma": "Georgiano",
    "governo": "República parlamentar",
    "monumento": "Cidade rupestre de Uplistsikhe",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Ancient_cave_in_Uplistsikhe_20230920.jpg?width=620",
    "fotoCredito": "Ancient cave in Uplistsikhe 20230920.jpg — Supanut Arunoprayote / CC BY 4.0 · Wikimedia Commons",
    "curiosidade": "É considerada o berço do vinho: há vestígios de produção com mais de 8000 anos, em vasilhas de barro chamadas qvevri."
  },
  {
    "nome": "Arménia",
    "endonimo": "Hayastan (Հայաստան)",
    "iso": "am",
    "ue": false,
    "capital": "Erevan",
    "populacao": 3000000,
    "area": 29743,
    "moeda": "Dram (AMD)",
    "idioma": "Arménio",
    "governo": "República parlamentar",
    "monumento": "Mosteiro de Guegard",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Monasterio_de_Geghard%2C_Armenia%2C_2016-10-02%2C_DD_63.jpg?width=620",
    "fotoCredito": "Monasterio de Geghard, Armenia, 2016-10-02, DD 63.jpg — Diego Delso / CC BY-SA 4.0 · Wikimedia Commons",
    "curiosidade": "Foi o primeiro país do mundo a adotar o cristianismo como religião oficial, no ano 301."
  },
  {
    "nome": "Azerbaijão",
    "endonimo": "Azərbaycan",
    "iso": "az",
    "ue": false,
    "capital": "Baku",
    "populacao": 10200000,
    "area": 86600,
    "moeda": "Manat (AZN)",
    "idioma": "Azeri",
    "governo": "República presidencial",
    "monumento": "Cidade Velha de Baku e a Torre da Donzela",
    "foto": "https://commons.wikimedia.org/wiki/Special:FilePath/Baku%2C_Azerbaiy%C3%A1n%2C_2016-09-26%2C_DD_211.jpg?width=620",
    "fotoCredito": "Baku, Azerbaiyán, 2016-09-26, DD 211.jpg — Diego Delso / CC BY-SA 4.0 · Wikimedia Commons",
    "curiosidade": "Chama-se \"a terra do fogo\": há encostas onde o gás natural arde à superfície há séculos, como a colina de Yanar Dağ."
  }
];
